@startuml
skinparam classAttributeIconSize 0

class AddAvailability {
    - calendar: CalendarView
    - startTimeButton: Button
    - startTimeText: TextView
    - endTimeButton: Button
    - endTimeText: TextView
    - save: Button
    - startTime: LocalTime?
    - endTime: LocalTime?
    + selectTime(isStartTime: Boolean)
}

class FindVet {
    - vetsList: LinearLayout
    + updateUIWithData(snapshot: QuerySnapshot)
}

class MainActivity {
    - signInLauncher: ActivityResultLauncher<Intent>?
    + authFlow()
    + goHome(auth: FirebaseAuth)
    + handleSignInResult(result: FirebaseAuthUIAuthenticationResult)
}

class MakeAppointment {
    - vetId: String
    - vetTitle: TextView
    - calendarView: CalendarView
    - appointmentList: LinearLayout
    + makeAppointment(date: LocalDate, time: LocalTime)
    + queryAvailabilityWindows(date: LocalDate)
}

class OwnerSignUp {
    - address: EditText
    - register: Button
    - errorMessage: TextView
    + checkInputs()
}

class PetOwnerWindow {
    - updateDetails: Button
    - logOut: Button
    - deleteAccount: Button
    - findVet: Button
}

class VetWindow {
    - logOut: Button
    - deleteAccount: Button
    - addAvailability: Button
    - availabilityWindowsList: LinearLayout
    + updateUIWithData(snapshot: QuerySnapshot)
}

class VeterinarianSignUp {
    - clinicName: EditText
    - clinicLocation: EditText
    - yearsOfExperience: EditText
    - expertise: EditText
    - aboutMe: EditText
    - register: Button
    + checkInputs()
}

MainActivity *--> PetOwnerWindow
MainActivity *--> VetWindow
VetWindow o--> AddAvailability
OwnerSignUp --> PetOwnerWindow
FindVet --> MakeAppointment
MainActivity --> OwnerSignUp
MainActivity --> VeterinarianSignUp

@enduml
