@startuml

title State Machine Diagram for Veterinarian Availability

[*] --> התחברות_וטרינר : התחברות לאפליקציה בתור וטרינר

התחברות_וטרינר --> פתיחת_חלון_זמינות : לחיצה על כפתור "פתיחת חלון זמינות"

פתיחת_חלון_זמינות --> בחירת_זמינות : בחירת תאריך ושעות זמינות

בחירת_זמינות --> אישור_זמינות : אישור שחלון זמינות נפתח

אישור_זמינות --> הצגה_למשתמשים
הצגה_למשתמשים --> וטרינר : הצגת חלון הזמינות שנקבע ב-UI של הווטרינר
הצגה_למשתמשים --> בעל_חיית_מחמד : הצגת חלונות זמינות ב-UI של בעל חיית מחמד לבחירת תור אפשרי


וטרינר --> [*]
בעל_חיית_מחמד --> [*]

@enduml
