@startuml

title State Machine Diagram for User Interaction

[*] --> בקשת_מרשם : חיפוש וטרינר לפי מיקום
בקשת_מרשם --> מחכה_לאישור_מהוטרינר : הבקשה נשלחה

'מחכה_לאישור_מהוטרינר --> מחכה_לאישור_מהוטרינר

מחכה_לאישור_מהוטרינר --> אישור_וטרינר : הוטרינר ראה את ההודעה

אישור_וטרינר --> [*] : בקשת המרשם התקבלה בהצלחה
@enduml
